# Generated by Django 4.0.2 on 2022-02-18 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodi',
            name='fakultas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran.fakultas'),
        ),
    ]
